# Chapter 1: 

## Introduction

Throughout political history, tyrants, and despots have influenced great power over large swaths of land and communities. One common thread amongst these individuals is how they wield their great power, often through dominant tactics such as threats and political subversion. Recent history has shown with individuals like Donald Trump, Kim Jong-Un, and Rodrigo Duterte who display authoritarian traits often wield their power through fear and threats of violence [@bernstein2020; @bynion2018; @kirby2021]. How this power is wielded is often different for each individual. Some individuals such as Duterte and Bolsonaro wielded their power more dramatically than the likes of Trump. Individuals wielding power need not be tyrants such as the former. Individuals like Angela Merkel used her position and leadership skills to be a world leader in most negotiations. While individuals more well known for their status demonstrated their power through prestige motives. To better understand how individuals such as world leaders or opinion makers gain and wield their power over others. Research in this field is often difficult to research yet strides have been made to understand power, namely through research in moral judgment and decision-making such as power orientation. 

## Dominance, Prestige, and Leadership orientation

Research in power desire motives has focused on three subdomains: dominance, leadership, and prestige [@suessenbach2019]. Each of these three different power motives is explained as to different ways or methods that individuals in power sought power or were bestowed upon them. Often these dominant individuals will wield their power with force and potentially cause risk to themselves to hold onto that power. 

### *Dominance*

The dominance motive is one of the more researched methods and well-depicted power motives. Individuals with a dominant orientation display the more primal human behavior. These individuals will seek power through direct methods such as asserting dominance, control over resources, or physically assaulting someone [@johnson2012; @winter1993]. Early research in dominance motives has shown that acts of dominance ranging from asserting physical dominance over another to physical displays of violence have been shown in many mammalian species, including humans [@petersen2018; @rosenthal2012]. 

Individuals high in dominance are often high in Machiavellianism, and narcissism, and often are prone to risky behavior (discussion further in the next section). Continued research has hinted at a possible tendency for males to display these dominant seeking traits more than females [@sidanius2000; @bareket2020]. When individuals high in dominance assert themselves they are doing so to increase their sense of power [@anderson2012; @bierstedt1950]. Asserting one's sense of dominance over another can be a dangerous task. In the animal kingdom, it can often lead to injury. While, humans asserting dominance can take a multitude of actions such as leering behaviors, physical distance, or other non-verbal methods to display dominance [@petersen2018; @witkower2020]. Power from a dominant perspective is not always bestowed upon someone. Often, high dominance individuals will take control and hold onto it.

### *Prestige*

Contrary to the dominant motivation of using intimidation and aggression to gain more power, a prestige motivation or prestige, in general, is bestowed upon an individual from others in the community [@maner2016; @suessenbach2019]. Different from dominance motivation, prestige motivation is generally unique to the human species [@maner2016]. Due in part to ancestral human groups being smaller hunter-gatherer societies, individuals that displayed and used important behaviors beneficial to the larger group were often valued and admired by the group. Therein, the social group bestows the authority onto the individual. Generally, this type of behavior can be passively achieved by the prestigious individual. However, this does not remove the intent of the actor in that they too can see prestige from the group, but the method of achieving that social status greatly differs from that of dominance-seeking individuals.

Apart from dominance-motivated individuals that continually have to fight for their right to have power over others, individuals that seek or were given power through a prestige motivation are not generally challenged in the same sense as dominant individuals. Displaying behaviors that the community would see as beneficial would endear them to the community making the survival of the community as a whole better [@maner2016]. Evolutionarily this would increase the viability of the prestigious individual and their genes. Similar to the dominance perspective, the prestige perspective overall increases the power and future survivability of the individual. However, due to the natural difference between prestige and dominance, dominance-seeking individuals are challenged more often resulting in more danger to their position [@johnson2012]. 

### *Leadership*

With a shared goal a leader is someone that takes initiative and attracts followers for that shared goal [@vanvugt2006]. Leadership is an interesting aspect of behavior in that it is almost exclusive to human interaction. Discussions by evolutionary psychologists point to the formation of early human hunter-gatherer groups where the close interconnectedness created a breeding ground for leadership roles. As early humans began to evolve it would become advantageous for individuals to work together for a common goal [@king2009]. Often, individuals with more knowledge of a given problem would demonstrate leadership and take charge or be given power.  Multiple explanations of the evolution of leadership exist such as coordination strategies, and safety, along with evidence for growth in social intelligence in humans [@vanvugt2006; @king2009].

An interesting aspect of leadership motivation is the verification of the qualities of the leader by the communities. Individuals that are often put into leadership roles or take a leadership role often display the necessary goals, qualities, and knowledge to accomplish the shared/stated goal. However, this is not always the case, especially for those charismatic leaders who could stay on as a leader longer than the stated goal requires [@vugt2014]. Traditionally, leadership was thought to be fluid in that those with the necessary knowledge at the time would be judged and appointed as the leader. However, these charismatic leaders use their charisma, uniqueness, nerve, and talent to hold onto their status.  <!-- This sentence is weird and should be changed. --> 


## Risk

Every time people leave the relative safety of their home, every decision they make they are taking some form of risk. Financial risk is often discussed in the media usually concerning the stock market. However, the risk is not just present in finances but also in social interactions such as social risk, sexual risk, health, and safety risk, recreational, and ethical risks [@weber2002; @shearer2005; @breakwell2007; @kuhberger2009]. Each individual is different in their likelihood and perception of participating in those risks. Some will be more inclined to be more financially risky while others would risk their health and safety.

Whether to engage in a risky situation is very complex depending on a cost-benefit analysis [@johnson2015a]. Do the positives outweigh the negatives? In practice, not all individuals will do a cost-benefit analysis of a risky situation. Often, the timing of an event makes such an analysis disadvantageous. The benefits are often relative to the individual decision-maker. Differences emerge in the general likelihood to engage in risky behavior such that males tend to be more likely to engage in risky behaviors than their female counterparts [@desiderato1995; @chen2021]. Women tended to avoid risky situations except for social risks. 

## Experiment One

## Method

### Participants

Participants were a convenience sample of `r length(experimenttwoDS$ResponseId)` (Mage = `r mean(experimenttwoDS$Age)`, SD = `r sd(experimenttwoDS$Age)`) individuals from Prolific Academic crowdsourcing platform ("www.prolific.co"). Requirements for participation were: (1) be 18 years of age or older and (2) and as part of Prolific Academics policy, have a prolific rating of 90 or above. Participants received £4 which amounts to £8 an hour as compensation for completion of the survey.  Table 1 demonstrates the demographic information for experiment one.

```{r, echo=FALSE, fig.pos='p'}
apa_table(
 demographictable_exploratory_experiment,
 stub_indents = list("Age" = c(1:2), "Gender" = c(3, 4), "Ethnic Origin" = c(5:12), "Education" = c(13:18), "Ethnicity" = c(19:22)), col.names = c("Demographic Characteristic", ""), cap = "Participant Demographic Information (Experiment 1)"
)
```

### Demographic Questionnaire

Prior to the psychometric scales, participants were asked to share their demographic characteristics (e.g., age, gender, ethnicity, ethnic origin, and educational attainment).

### Dominance, Prestige, and Leadership Orientation

The 18-item Dominance, Prestige, and Leadership scale [DoPL; @suessenbach2019], is used to measure dominance, prestige, and leadership orientation. Each question corresponds to one of the three domains. Each domain is scored across six unique items related to those domains (e.g., "I relish opportunities in which I can lead others" for leadership). These statements and goals are rated on a scale from 0 (Strongly disagree) to 5 (Strongly agree). Internal consistency reliability per subscale with the current sample with $\alpha$'s ranging from dominance = `r printnum(psych::alpha(newDF[, dominanceQuestions])$total$std.alpha)`, prestige = `r printnum(psych::alpha(newDF[, prestigeQuestions])$total$std.alpha)`, leadership = `r printnum(psych::alpha(newDF[, leadershipQuestions])$total$std.alpha)`, and UMS = `r printnum(psych::alpha(newDF[, UMSQuestions])$total$std.alpha)`.

### Spitefulness Scale

The Spitefulness scale [@marcus2014] is a measure with seventeen one-sentence vignettes to assess the spitefulness of participants. The original spitefulness scale has 31-items. In the original Marcus and colleagues' paper, fifteen were removed. For the present study, however, 4-items were removed because they did not meet the parameters for the study i.e., needed to be dyadic, interpersonal spitefulness. To follow this, we replaced the four that were removed and included three reverse-scored items from the original thirty-one. Example questions included, "It might be worth risking my reputation in order to spread gossip about someone I did not like," and "Part of me enjoys seeing the people I do not like to fail even if their failure hurts me in some way". Items are scored on a 5-point scale ranging from 1 ("Strongly disagree") to 5 ("Strongly agree"). Higher spitefulness scores represent higher acceptance of spiteful attitudes. Internal consistency reliability for the current sample is $\alpha$ = `r printnum(psych::alpha(newDF[,spiteQuestions])$total$std.alpha)`.

### Sexuality Self-Esteem Subscale

The Sexuality Self-Esteem subscale (SSES; @snell1989) is a subset of the Sexuality scale that measures the self-esteem of participants. The 10-items chosen reflected questions on the sexual esteem of participants on a 5-point scale of +2 (Agree) and -2 (Disagree). For ease of online use the scale was changed to 1 ("Disagree") and 5 ("Agree"), data analysis will follow the sexuality scale scoring procedure. Example questions are, "I am a good sexual partner," and "I sometimes have doubts about my sexual competence." Higher scores indicate a higher acceptance of high self-esteem statements. Internal consistency reliability for the current sample is $\alpha$ = `r printnum(psych::alpha(newDF[,ssesQuestions])$total$std.alpha)`.

### Sexual Jealousy Subscale

The Sexual Jealousy subscale by @worley2014 are 3-items from the 12-item Jealousy scale. The overall jealousy scale measures jealousy in friendships ranging from sexual to companionship. The 3-items are "I would worry about my partner being sexually unfaithful to me.", "I would suspect there is something going on sexually between my partner and their friend.", and "I would suspect sexual attraction between my partner and their friend." The items are scored on a 5-point scale ranging from 1 ("Strongly disagree") to 5 ("Strongly agree"). Higher scores indicate a tendency to be more sexually jealous. Internal consistency reliability for the current sample is $\alpha$ = `r printnum(psych::alpha(newDF[,sjsQuestions])$total$std.alpha)`.

### Sexual Relationship Power Scale

The Sexual Relationship Power Scale (SRPS; @pulerwitz2000) is a 23-item scale that measures the overall power distribution in a sexually active relationship. The SRPS is split into the Relationship Control Factor/Subscale (RCF) and the Decision-Making Dominance Factor/Subscale (DMDF). The RCF measures the relationship between the partners on their agreement with statements such as, "If I asked my partner to use a condom, he[they] would get violent.", and "I feel trapped or stuck in our relationship." Items from the RCF are scored on a 4-point scale ranging from 1 ("Strongly agree") to 4 ("Strongly disagree"). Lower scores indicate an imbalance in the relationship where the participant indicates they believe they have less control in the relationship. Internal consistency reliability for the current sample is $\alpha$ = `r printnum(psych::alpha(newDF[,srps.rcQuestions])$total$std.alpha)`.

The DMDF measures the dominance level of sexual and social decisions in the relationship. Example questions include, "Who usually has more say about whether you have sex?", and "Who usually has more say about when you talk about serious things?" Items on the DMDF are scored on a 3-item scale of 1 ("Your Partner"), 2 ("Both of You Equally"), and 3 ("You"). Higher scores indicate more dominance by the participant in the relationship. Internal consistency reliability for the current sample is $\alpha$ = `r printnum(psych::alpha(newDF[,srps.dmQuestions])$total$std.alpha)`.

### Scenario Realism Question

Following Worley and Samp in their 2014 paper on using vignettes/scenarios in psychological studies, a question asking the participant how realistic or how much they can visualize the scenario is. The 1-item question is "This type of situation is realistic." The item is scored on a 5-point scale with how much the participants agreed with the above statement, 1 ("Strongly agree") to 5 ("Strongly disagree"). Higher scores indicate disagreement with the statement and reflect the belief that the scenario is not realistic.

### Spiteful Vignettes

After participants complete the above scales, they are presented with 10-hypothetical vignettes. Each vignette was written to reflect a dyadic or triadic relationship with androgynous names to control for gender. Five vignettes have a sexual component while five are sexually neutral. An example vignette is,

> "Casey and Cole have been dating for 6 years. A year ago, they both moved into a new flat together just outside of the city. Casey had an affair with Cole's best-friend. Casey had recently found out that they had an STI that they had gotten from Cole's best-friend. Casey and Cole had sex and later Cole found out they had an STI."

For each vignette, the participant is asked to rate each vignette on how justified they believe the primary individual, Casey in the above, is with their spiteful reaction. Scoring ranges from 1 ("Not justified at all") to 5 ("Being very justified"). Higher scores overall indicate higher agreement with spiteful behaviors.

## Procedure

Participants were recruited on Prolific Academic. Participants must be 18-years of age or older, restriction by study design and Prolific Academic's user policy. The published study is titled, "Moral Choice and Behavior". The study description follows the participant information sheet including participant compensation. Participants were asked to accept their participation in the study. Participants were then automatically sent to the main survey (Qualtrics, Inc.). 

Once participants accessed the main survey, they were presented with the consent form for which to accept they responded by selecting "Yes". Participants were then asked to provide demographic characteristics such as gender, ethnicity, and educational attainment. Participants would then complete in order, the spitefulness scale, the sexual relationship power scale, the sexual jealousy subscale, and sexuality self-esteem subscale. Next, participants were presented ten vignettes where they were instructed to rate on the level of justification for the action carried out in the vignette. After each vignette, participants would rate the realism of the scenario. Upon completion of the survey (median completion time 20 minutes SD = 10 Minutes 30 seconds), participants were shown a debriefing message and shown the contact information of the Primary Investigator (Andrew Ithurburn). Participants were then compensated at £8/hr. via Prolific Academic. 



## Data Analysis

Demographic characteristics were analyzed using a one-way analysis for continuous variables (age) and Chi-squares tests for categorical variables (sex, ethnicity, ethnic origin, and educational attainment). Means and standard deviations were calculated for the surveys along with correlational analyses (e.g., spitefulness, SESS, SRPS, SJS).

Bayesian multilevel models were used to test differences between levels of justifications of vignettes that are either sexually or non-sexually vindictive in behavior.


## Results and Discussion

`r str_to_title(english::as.english(nrow(experimenttwoDS)))` individuals participated in the present experiment. A majority of the participants in experiment 1 identified as male (*n* = `r printnum(genderresults$freq[2])`). Table 1 shows the demographic information for experiment 1. Table 2 presents the results of a Bayesian correlational matrix of all measures. As evidenced in the Bayesian correlational matrix, most surveys positively correlated with one another.

### Spitefulness

For this analysis we used the Bayesian parameter estimation using R and brms [@rcoreteam2021; @burkner2018]. An annotated r script file, including all necessary information is available at [https://osf.io/jz6qb](https://osf.io/jz6qb). On average, individuals were not rated as being more spiteful, (*M* = `r printnum(mean(analysisDF$Spite))`, *SD* = `r printnum(sd(analysisDF$Spite))`, Min-max = [`r printnum(min(analysisDF$Spite))` - `r printnum(max(analysisDF$Spite))`]). Justification as a function of the four indices was moderately explained by the model (*R^2^* = `r printnum(bayes.dm5_exploratory_experiment[1])`). We conducted an exploratory Bayesian correlation analysis on the data, where we investigated correlations between 8 of the indices (e.g., Spite, Dominance, Prestige, Leadership, Sexual Jealousy, Sexual Self-Esteem, and Sexual Relationship Power Scale).

Selected notable non-null correlations were found between Spite and Sexual Jealousy ($\rho$ = `r printnum(corr.mod_exploratory_experiment["Spite_z | SJS_z", "rho"])`, 95% CI: `r printnum(corr.mod_exploratory_experiment["Spite_z | SJS_z", "95% CI"])`), Spite and Dominance ($\rho$ = `r printnum(corr.mod_exploratory_experiment["Spite_z | Dominance_z", "rho"])`, 95% CI: `r printnum(corr.mod_exploratory_experiment["Spite_z | Dominance_z", "95% CI"])`), and Sexual Relationship Power and Dominance ($\rho$ = `r printnum(corr.mod_exploratory_experiment["SRPS_z | Dominance_z", "rho"])`, 95% CI: `r printnum(corr.mod_exploratory_experiment["SRPS_z | Dominance_z", "95% CI"])`). Table 2 contains a complete list of all Bayesian correlations.

## Limitations and Future Directions

## Experiment 2

## Methods

Materials remain the same in terms of the (1) Demographic Questionnaire, (2) Dominance, Prestige, and Leadership Questionnaire, and (3) DOSPERT Questionnaire. However, we added the Brief-Pathological Narcissism Inventory to assess possible interactions of dominance and narcissism in risky decision-making. Materials and methods were approved by the University of 
## Participants

Following experiment 1, participants were a convenience sample of 111 individuals from Prolific Academic's crowdsourcing platform (www.prolific.io). Prolific Academic is an online crowdsourcing service that provides participants access to studies hosted on third-party websites. Participants were required to be 18 years of age or older and be able to read and understand English. Participants received £4.00, which is above the current minimum wage pro-rata in the United Kingdom, as compensation for completing the survey. The Psychology Research Ethics Committee at the University of Edinburgh approved all study procedures [ref: 212-2021/2]. The present study was pre-registered along with a copy of anonymized data and a copy of the R code is available at ([https://osf.io/s4j7y](https://osf.io/s4j7y)).

## Materials


### *Brief-Pathological Narcissism Inventory* 

The 28 item Brief Pathological Narcissism Inventory (B-PNI; Schoenleber et al., 2015) is a modified scale of the original 52-item Pathological Narcissism Inventory (PNI; Pincus et al., 2009). Like the PNI the B-PNI is a scale measuring individuals' pathological narcissism. Items in the B-PNI retained all 7 pathological narcissism facets from the original PNI (e.g., exploitativeness, self-sacrificing self-enhancement, grandiose fantasy, contingent self-esteem, hiding the self, devaluing, and entitlement rage). Each item is rated on a 5 point Likert scale ranging from 1 (not at all like me) to 5 (very much like me). Example items include "I find it easy to manipulate people" and "I can read people like a book." 

## Procedure

Participants were recruited via a study landing page on Prolific's website or via a direct e-mail to eligible participants [@prolificacademic2018]. The study landing page included a brief description of the study including any risks and benefits along with expected compensation for successful completion. Participants accepted participation in the experiment and were directed to the main survey on pavlovia.org (an online JavaScript hosting website similar to Qualtrics) where they were shown a brief message on study consent.

Once participants consented to participate in the experiment they answered a series of demographic questions. Once completed, participants completed the Dominance, Prestige, and Leadership Scale and the Domain Specific Risk-taking scale. An additional survey was added (the novel aspect of experiment 2) where participants, in addition to the two previous surveys, were asked to complete the brief-pathological narcissism inventory. The three scales were counterbalanced to account for order effects. After completion of the main survey, participants were shown a debriefing statement that briefly mentions the purpose of the experiment along with the contact information of the main researcher (AI). Participants were compensated £4.00 via Prolific Academic. 

## Data analysis

Demographic characteristics were analyzed using multiple regression for continuous variables (age) and Chi-square tests for categorical variables (gender, race, ethnicity, ethnic origin, and education). Means and standard deviations were calculated for the relevant scales (i.e., DoPL and DOSPERT). All analyses were done using [@rcoreteam2021] along with [@burkner2017] package.

The use of bayesian statistics has a multitude of benefits to statistical analysis and research design. One important benefit is through the use of prior data in future analyses. Termed as priors, is the use of prior distributions for future analysis. This allows for the separation of how the data might have been collected or what the intention was. In essence, the data is the data without the interpretation of the scientist. 

All relevant analyses were conducted in a Bayesian framework using the brms package [@burkner2018] along with the cmdstanr packages notes [@gabry2021]. In addition to the aforementioned packages, we used bayestestR, rstan, and papaja for analysis along with the creation of this manuscript [@makowski2019; @aust2020; @standevelopmentteam2020].

## Results


## Preregistered Analyses



### *Demographic and DoPL*



## Domain-Specific Risk-Taking

## Interactions


## Discussion
## Limitations

## Future Implications