# Introduction

Throughout political history, tyrants, and despots have influenced great power over large swaths of land and communities. One common thread amongst these individuals is how they wield their great power, often through dominant tactics such as threats and political subversion. Recent history has shown with individuals like Donald Trump, Kim Jong-Un, and Rodrigo Duterte who display authoritarian traits often wield their power through fear and threats of violence [@bernstein2020; @bynion2018; @kirby2021]. How the powerful use and wield power can differ drastically from person to person. Some individuals such as Duterte and Bolsonaro wielded their power more dramatically than the likes of Trump. Individuals wielding power need not be tyrants such as the former[@riley1997]. Individuals like Angela Merkel used her position and leadership skills to be a world leader in most negotiations. While individuals more well known for their status demonstrated their power through prestige motives. To better understand how individuals such as world leaders or opinion makers gain and wield their power over others. Research in this field is often difficult to research yet strides have been made to understand power, namely through research in moral judgment and decision-making such as power orientation. 

## Dominance, Prestige, and Leadership orientation

Research in power desire motives has focused on three subdomains: dominance, leadership, and prestige [@suessenbach2019]. Each of these three different power motives is explained as to different ways or methods that individuals in power sought power or were bestowed upon them. Often these dominant individuals will wield their power with force and potentially cause risk to themselves to hold onto that power. 

### *Dominance*

The dominance motive is one of the more researched methods and well-depicted power motives. Individuals with a dominant orientation display the more primal human behavior. These individuals will seek power through direct methods such as asserting dominance, control over resources, or physically assaulting someone [@johnson2012; @winter1993]. Early research in dominance motives has shown that acts of dominance ranging from asserting physical dominance over another to physical displays of violence have been shown in many mammalian species, including humans [@petersen2018; @rosenthal2012]. 

Individuals high in dominance are often high in Machiavellianism, and narcissism, and often are prone to risky behavior (discussion further in the next section). Continued research has hinted at a possible tendency for males to display these dominant-seeking traits more than females [@sidanius2000; @bareket2020]. When highly dominant individuals assert themselves they are doing so to increase their sense of power [@anderson2012; @bierstedt1950]. Asserting one's sense of dominance over another can be a dangerous task. In the animal kingdom, it can often lead to injury. While, humans asserting dominance can take a multitude of actions such as leering behaviors, physical distance, or other non-verbal methods to display dominance [@petersen2018; @witkower2020]. Power from a dominant perspective is not always bestowed upon someone. The results of these expressions of dominance are not often given by the other or conceded from the less powerful or dominant person but are taken by those with more dominance. Dominant actions or dominantly taking power can often lead to physical, emotional, and psychological violence [@williams2017; @malamuth1996].

### *Prestige*

Contrary to the dominant motivation of using intimidation and aggression to gain more power, a prestige motivation or prestige, in general, is bestowed upon an individual from others in the community [@maner2016; @suessenbach2019]. Different from dominance motivation, prestige motivation is generally unique to the human species [@maner2016]. Due in part to ancestral human groups being smaller hunter-gatherer societies, individuals that displayed and used important behaviors beneficial to the larger group were often valued and admired by the group. Therein, the social group bestows the authority onto the individual. Generally, this type of behavior can be passively achieved by the prestigious individual. However, this does not remove the intent of the actor in that they too can see prestige from the group, but the method of achieving that social status greatly differs from that of dominance-seeking individuals.\

Apart from dominance-motivated individuals that continually have to fight for their right to have power over others, individuals that seek or were given power through a prestige motivation are not generally challenged in the same sense as dominant individuals. Displaying behaviors that the community would see as beneficial would endear them to the community making the survival of the community as a whole better [@maner2016]. Evolutionarily this would increase the viability of the prestigious individual and their genes. Similar to the dominance perspective, the prestige perspective overall increases the power and future survivability of the individual. However, due to the natural difference between prestige and dominance, dominance-seeking individuals are challenged more often resulting in more danger to their position [@johnson2012]. 

### *Leadership*

With a shared goal a leader is someone that takes initiative and attracts followers for that shared goal [@vanvugt2006]. Leadership is an interesting aspect of behavior in that it is almost exclusive to human interaction. Discussions by evolutionary psychologists point to the formation of early human hunter-gatherer groups where the close interconnectedness created a breeding ground for leadership roles. As early humans began to evolve it would become advantageous for individuals to work together for a common goal [@king2009]. Often, individuals with more knowledge of a given problem would demonstrate leadership and take charge or be given power.  Multiple explanations of the evolution of leadership exist such as coordination strategies, and safety, along with evidence for growth in social intelligence in humans [@vanvugt2006; @king2009].

An interesting aspect of leadership motivation is the verification of the qualities of the leader by the communities. Individuals that are often put into leadership roles or take a leadership role often display the necessary goals, qualities, and knowledge to accomplish the shared/stated goal. However, this is not always the case, especially for those charismatic leaders who could stay on as a leader longer than the stated goal requires [@vugt2014]. Traditionally, leadership was thought to be fluid in that those with the necessary knowledge at the time would be judged and appointed as the leader. However, these charismatic leaders use their charisma, uniqueness, nerve, and talent to hold onto their status.  <!-- This sentence is weird and should be changed. --> 
## Risk

Every time people leave the relative safety of their home, every decision they make they are taking some form of risk. Financial risk is often discussed in the media usually concerning the stock market. However, the risk is not just present in finances but also in social interactions such as social risk, sexual risk, health and safety risk, recreational, and ethical risks [@weber2002; @shearer2005; @breakwell2007; @kuhberger2009]. Each individual is different in their likelihood and perception of participating in those risks. Some will be more inclined to be more financially risky while others would risk their health and safety.

Whether to engage in a risky situation is very complex depending on a cost-benefit analysis [@johnson2015a]. Do the positives outweigh the negatives? In practice, not all individuals will do a cost-benefit analysis of a risky situation. Often, the timing of an event makes such an analysis disadvantageous. The benefits are often relative to the individual decision-maker. Differences emerge in the general likelihood to engage in risky behavior such that males tend to be more likely to engage in risky behaviors than their female counterparts [@desiderato1995; @chen2021]. Women tended to avoid risky situations except for social risks. Age is also a factor in the likelihood of engaging in a risky situation. Often as people age, we become less likely to engage in certain behaviors such as financial risks but more likely to engage in social and some recreational risks [@rolison2014]. With certain behavioral domains, risk decisions do not appear to have any differences based on age. As of yet, there is currently no longitudinal analysis of risk over the years [see meta-analysis of risk-taking @mamerow2016]. 