# Literature Review

## General Introduction

In 2016, the year of most recent global data collection, there were 376 million new cases of the four curable sexually transmitted infections, chlamydia, gonorrhea trichomoniasis, and syphilis [@worldhealthorganization2018]. The World Health Organization (WHO) further estimates that there are one million new cases of a curable sexually transmitted infection each day. Due to multiple factors, certain minoritpopulations are more at risk for contracting new sexually transmitted infections, e., men who have sex with men and female sex workers [@worldhealthorganization2018].  Some factors includcertain societal beliefs men who have sex with men might engage in nonrelational sex "just trying to figure things out it's just a hook-up phase" [@elder2015a], ambiguous laws concerning the legality of sex work interfering with safe and available locations for such activity, as well. Often, societal beliefs impact discussions of sexual exploration making sexual explorations in themselves difficult and taboo [@parent2015]. There may also be some difficulties in their willingness in their activities be it forced by another or sheer necessity. For countries like Scotland while there has been a reduction in the number of new cases of STIs like HIV amongst key populations, new risks of antibiotic-resistant gonorrhea, _Neisseria gonorrhoaeae_, have become more apparent [@ison2011].

Outside of the Scotland, such as England, STI rates still show relatively high numbers with new cases nymber in 317,000 cases [@ratna2021]. Optimistically, STI rates have reduced in the last year before publication of the report by nearly 34%. However, it should be noted that there was a 25% decrease in the number of sexual health screenings compared to the previous year which the authors note as contributing to the decrease in STI diagnoses [@ratna2021, pp.5]. Furthering, outside of the United Kingdom, global STI rates are still increasingly especially in areas with little to know access to appropriate sexual health education and health care to support the increasing number. According to the World Health Organization, 1 million people are infected with an STI each day [@worldhealthorganization2022]. Including an estimated annual death toll of 2.3 million people. Along with death, STI infection can leads to financial, social, and psychological issues and trauma [@henkel2004; @deal2004; @delva1983; @young2007a]. 

## Moral Decision Problems

Researching issues such as STIs and other moral laden issues can often be difficult to devise and run. Often, sexually transmitted infections and risky sexual behavior are used as examples to discuss moral issues. Methods at understanding these situations and other moral issues are commonly through dilemmas or vignettes where individuals are presented with a short scenario and asked to choose one outcome over another [@ellemers2019]. A trademark example is the trolley car experiment where there is a runaway trolley car that is going toward five people [@greene2001]. The decision is thus, to allow the trolley to careen towards the five people or you could divert the trolley by pushing and sacrificing a large man for the sake of the other five. This type of dilemma poses an interesting method of understanding how and what the decision maker would choose. The researcher can then change the dilemma in its severity and complexity. There could also be a change in the situation and the types of individuals that are at risk. Individual choice tasks investigating risky sexual behaviors and STIs could be furthered by investigating the moral decision-making aspect of those issues.

## Current Methods and Problems in Research

As such, researching in particular sexually laden moral decisions can often be difficult and complex. Current STI research has focused on methods of ways of curbing individuals act a certain way when presented with a risky sexual situation [@kirby2007]. Current methods have shown mixed results. In many countries, how people are taught about risk and sex can vary wildly [@unesco2015]. For example, some countries may have one standard which is a mix of religious and scientific ideas of STIs. While others may not even have a formal sexual education program. Some aspects of sexual activity are not even discussed, for example, non-heterosexual sex [@ellis2004]. This omission is problematic because historically men who have sex with men in particular, are at a higher risk of contracting an STI [@wald2001]. Often, research can overlook certain aspects of sexual activity and thus will inadvertently miss certain key aspects of researching STIs. Filling that research gap will ultimately benefit our understanding of human behavior and risky behaviors. 

## Power and Aggression

An interesting outcome of human behavior from moral judgment research and risky decisions is human aggression which is one of the mainstays of power research [citation].  Aggression, behavior that is committed by the actor to another with the intent to harm the other, is separeated by the reason behind the aggression. For example, if the aggression was intended to be hostile or serve a purpose (hostile aggression and instrumental aggression) [@anderson2002]. Looking at human behavior from this perspective allows researchers to look at underlying behavioral characteristics outside of the traditional trauma or action/reaction-based model of human behavior such as behavioral economics. <!-- Relook at this sentence to better explain what I mean by this --->

The me-too movement acted as a watershed moment for often male sexual aggression toward women. Highlighting issues of how these power-over views of women, especially women of color and trans women of color, become learned and develop into sexual aggression. Sexual aggression in and of itself is a subgroup of aggression where the intent to harm is sexual [@anderson2002; @malamuth1995]. Many of the targets of sexual aggression are women of color and trans women of color [@jefferson2013 add more citations]. In the reported cases men are often the perpetrators of the crimes [@anderson2002]. The aggression itself appears to be domain specific to one gender, women. Often, acts of sexual aggression are verbal in nature, such as asking repeatedly for sex or threatening to break up with them [@testa2015]. When individuals gain power they may aggress more over those that have less power, which may pay head to the continued sexual aggression and sexual violence against women of color and trans women of color who have historically low levels of power [@jefferson2013]. <!-- add more information and citations -->

Recent research by Garnett and Mann investigate the cognitive and empathetical processes of those that commit a sexual aggression or sexual violence, labeled as sexual offending [-@barnett2013]. Common to research on sexual offenses, research contends that those that do offend do so with a lack of empathy towards their victims [@marshall1993]. As noted in the previous section on moral judgment, see section 3, empathetic processing by these offenders are more complex than the simple inability to "feel" or identify the emotions of others. There is a recurring theme amongst offenders of women being deceitful and sexually entitled [@barnett2013; @gannon2009]. The offenders often feel slighted when a woman denies their sexual advances which then tends to lead to some sexual aggression [@williams2017; @gannon2009].

The rejection of the sexual advances of the man often damage their sense of masculinity [@malamuth1996]. Relating back to beliefs on condom use amongst men, even the request of wearing condom could be interpreted as damaging their sense of masculinity [@castrovazquez2000]. If the woman, in a heterosexual relationship, brings the condom they are damaging the males' masculinity but if the male brings the condom he could also be considered a thoughtful individual. While the woman would be seen as easy. This could then lead to bullying behavior and ostracization from the moral judgment of the community on the woman's purity, see section moral judgment.




<!-- In CNT, similar to the study of disgust association where some research suggests that inducing the disgust response to smell causes individuals to become more conservative against breaking moral norms [@tybur2009; @eskine2011; @horberg2009; @laakasuo2017]. Important to the present discussion on sexual judgment, research by Laakasuo and colleagues suggest that disgust is only predictive of sexual disgust [-@laakasuo2017]. From CNT, Anderson and Bushman developed the General Aggression Model [GAM] is a theoretical outline that combines multiple smaller domain specific theories on aggression like CNT [-@anderson2002]. The GAM has processes: inputs, routes, and outcomes of a social situation. The inputs separate into a person and situation centered inputs. The individual then has an internal examination of the person or situation, cognitions like affective processes, availability heuristics, theory of mind evaluations, scripts and schemata [@barnett2013; @kahneman1972; scripts and schemata citation]. Appraisal and a decision process are the last step in the GAM, where the individual evaluates the situation based on the inputs and routes. Anderson and Bushman contend that there are two types of outcomes, thoughtful and impulsive actions. Like the affective heuristic, the impulsive action is often fast and does not require as much deliberation. While the thoughtful action requires more time and evaluation of all the possible outcomes.

Scripts and schemata are key components of the GAM. Schema, more broadly than sexual schema, are cognitive compositions or structures that represent objects or ideas interconnected by their features [@dimaggio1997]. Multiple representations of schema and stereotypical event sequences are labelled as scripts [@abelson1981]. A classic example of a cognitive script is events surrounding reading the menu at a restaurant [@abelson1981]. An individual is at a restaurant and needs to order from the menu. However, they lost their reading glasses. As Abelson contends, the reader must infer what is needed in reading a menu, what occurs at a restaurant, and so on. The automatic process of schematic activation begins with certain key features of an object or event being noticed by the individual. For example, recognizing a tree one of the first features that are noticed that distinguishes a tree are the leaves. From the leaves, the bark is activated, and so on making up the concept of a tree.

Often aggression and discrimination can be understood through the schematic model. Media and social representations of individuals, especially men of color, have often made assumptions and portrayed them as violent and criminals. Currently a majority of US adults in a recent Pew Research Center poll report that race relations are currently worse, Black Americans and people of color in general report more cases of discrimination, and a majority say Black Americans in particular are treated unfairly by the police [@pewresearchcenter2019]. Aggression or discrimination is often the result of associating one group with negative connotations. For example, in the case of those that believe Black Americans are criminals they have through cognitive associations have related the schematic concept of criminal with the features/schema of what they believe is a Black American. The discrimination and aggression then occur through the GAM processes with negative actions being the outcome.-->