---
title             : "The psychology of risk and power: Power desires and sexual choices"
shorttitle        : "Risk and Power"

author: 
  - name          : "Ithurburn, Andrew"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "7 George Square, Edinburgh, EH8 9JZ"
    email         : "a.ithurburn@sms.ed.ac.uk"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Writing - Original Draft Preparation
      - Writing - Review & Editing
  - name          : "Moore, Adam"
    affiliation   : "1"
    role:
      - Writing - Review & Editing

affiliation:
  - id            : "1"
    institution   : "The University of Edinburgh"

authornote: |
  University of Edinburgh Department of Psychology

abstract: |
 fndsjahf udsh fusd vdsahfiuds fiodsa f
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "2222"

bibliography      : "../References/references.bib"

floatsintext       : yes
figurelist         : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no
mainfont          : "Times New Roman" 
geometry          :  a4paper, left = 4cm, right = 2.5cm, top = 2cm, bottom = 4cm
always_allow_html : true
link-citations    : true
header-includes:
  - \setcounter{tocdepth}{3}
  - \linespread{1.2}
  - \interfootnotelinepenalty=10000
  - \usepackage{setspace}
  - \newcommand{\HRule}{\rule{\linewidth}{0.25mm}}
  - \raggedbottom
  - \captionsetup[figure]{textformat=empty}
  - \usepackage{pdflscape}
  
documentclass     : "apa7"
csl               : "../Formatting/apa7.csl"
class             : doc, 12pt, a4paper
classoption       : "donotrepeattitle"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
source("../R/indexfile.r")
```

```{r child = "/Users/andrew/Library/CloudStorage/OneDrive-Personal/Documents/1_UoE/Research/PhD/Dissertation/Chapters/Chapter1.Rmd"}

```

\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup

```{r child = "/Users/andrew/Library/CloudStorage/OneDrive-Personal/Documents/1_UoE/Research/PhD/Dissertation/Chapters/GraphsandTables/ExploratoryExperimenttablesandfigures.Rmd"}

```