---
title             : "Power motivations and risk sensitivity and tolerance."
shorttitle        : "DoPL and DOSPERT"

author: 
  - name          : "Ithurburn, Andrew"
    affiliation   : "1"
    
    corresponding : yes    # Define only one corresponding author
    address       : "7 George Square, Edinburgh, EH8 9JZ"
    email         : "a.ithurburn@sms.ed.ac.uk"
    role:         ""

  - name          : "Pedersen M.E., Julie"
    affiliation   : "1"
  - name          : "Moore, Adam"
    affiliation   : "1"
    role:
      - Writing - Review & Editing
      - Supervision

affiliation:
  - id            : "1"
    institution   : "The University of Edinburgh"


abstract: |
  In the present research, we sought to examine through two experiments the interaction between power motives (dominance, prestige, and leadership) and risk taking behaviors. In study 1 we found that individuals high in dominance power motive were more likley to enage in financial, ethical and health and safety based risk sitations. We then sought to examine the interaction between power motives and risk sensitivity and tolerance. In study 2 we found that individuals high in dominance power motive were more likely to engage in risky behaviors when they were high in risk sensitivity and tolerance. We also found that individuals high in prestige power motive were more likely to engage in risky behaviors when they were high in risk tolerance. We discuss the implications of these findings for the study of power and risk taking behaviors.
  
keywords          : "keywords"
wordcount         :  !expr wordcountaddin::word_count("../Chapters/Chapter2.Rmd") + wordcountaddin::word_count("../Chapters/DoPL-Section.Rmd")

bibliography      : ["../References/references.bib"]

floatsintext       : yes
figsintext         : yes
numbersections    : yes
figurelist         : yes
tablelist         : yes
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no
mainfont          : "Times New Roman"
geometry          :  a4paper, left = 4cm, right = 2.5cm, top = 2cm, bottom = 4cm
always_allow_html : true 
link-citations    : true
header-includes:
  - \setcounter{tocdepth}{3}
  - \linespread{1.2}
  - \usepackage{fancyhdr}
  - \interfootnotelinepenalty=10000
  - \usepackage{setspace}
  - \newcommand{\HRule}{\rule{\linewidth}{0.25mm}}
  - \raggedbottom
  - \captionsetup[figure]{textformat=empty}
  - \usepackage{pdflscape}
  - \usepackage{threeparttablex}
documentclass     : "apa7"
csl               : "../Formatting/apa7.csl"
class             : doc, 12pt, a4paper
classoption       : "donotrepeattitle"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
setwd("/Users/andrew/Documents/1_UoE/Research/PhD/Writing/Dissertation")
source("./R/libraries.R")
source("./R/Chapter_2_index.r")
options(knitr.kable.NA = "")
```

```{r child = "../Chapters/DoPL-Section.Rmd"}
```

```{r child = "../Chapters/Chapter2.Rmd"}
```

\newpage
\newpage

# References
\begingroup
<div id="refs" custom-style="Bibliography"></div>
\endgroup

\listoffigures

\newpage

# Figures and Tables

## Figures

```{r child = "../Chapters/GraphsandTables/Chapter-2-graphs.Rmd"}
```

## Tables

```{r child = "../Chapters/GraphsandTables/Chapter-2-tables.Rmd"}
```
