library("papaja")
r_refs("r-references.bib")
options(digits = 2)
library("languageserver")
library("DT")
library("ggplot2")
library("ggthemes")
library("tidyr")
library("papaja")
library("brms")
library("rstan")
library(stringr)
library("bayestestR")
library("sjPlot")
library("psych")
library("BayesFactor")
library("bayesplot")
library("kableExtra")
library("ggcorrplot")
library("ggprism")
options(mc.corrs = parallel::detectCores())
rstan_options(auto_write = TRUE)
options(control = list(adapt_delta = 0.99999))
options(brms.backend = "cmdstanr")
bayesplot::bayesplot_theme_set(theme_apa())
locfunc <- function(data, to) {
  which(colnames({{ data }}) == {{ to }})
}
lfunc <- function(dataset, to, from) {
  loc1 <- which(colnames({{ dataset }}) == {{ to }})
  loc2 <- which(colnames({{ dataset }}) == {{ from }})
  length({{ dataset }}[loc1:loc2])
}
theme_set(theme_apa(base_size = 12))

source("./R/Chapter_2_index.r")
Remove <- "/Users/andrew/Library/CloudStorage/OneDrive-Personal/Documents/1_UoE/Research/PhD/Writing/Dissertation/"
