library(papaja)
library(ggplot2)
library(sjPlot)
library(readr)
library(RColorBrewer)
library(tidyr)
library(grid)
library(gtable)
library(DiagrammeR)
library(lubridate)
library(DT)
library(kableExtra)
library(svgPanZoom)
library(knitr)
library(ggmcmc)
library(ggridges)
library(rstan)
library(insight)
library(shiny)
library(gridExtra)
library(ggpubr)
library(gghighlight)
library(ggtext)
library(readr)
library(ggcorrplot)
library(ggprism)
library(brms)
library(parameters)
library(rmarkdown)
library(DT)
library(ggplot2)
library(ggthemes)
library(brms)
library(cmdstanr)
library(rstan)
library(bayestestR)
library(sjPlot)
library(psych)
library(BayesFactor)
library(bayesplot)
library(kableExtra)
library(gtsummary)
library(tidyr)
library(table1)
library(huxtable)
library(lubridate)
library(correlation)
options(mc.corrs = parallel::detectCores(), brms.backend = "cmdstanr")
rstan_options(auto_write = TRUE)
load("./Questions.RData")
source("./R/data_file_index.r")
theme_set(theme_apa())
sign_match <- function(m) {
  (m > 0) - (m < 0)
}



Remove <- "/Users/andrew/Library/CloudStorage/OneDrive-Personal/Documents/1_UoE/Research/PhD/Dissertation/"
